working_directory: /usr/src/app
proxy_file_name: /usr/src/app/cadcproxy.pem
resource_id: ivo://cadc.nrc.ca/sc2repo
todo_file_name: todo.txt
use_local_files: True
logging_level: INFO
log_to_file: True
log_file_directory: /usr/src/app/logs
stream: raw
archive: OMM
collection: OMM
task_types: 
  - store
  - ingest
  - modify
features:
  use_file_names: False
  use_urls: False
