working_directory: /usr/src/app
proxy_file_name: /usr/src/app/cadcproxy.pem
resource_id: ivo://cadc.nrc.ca/sc2repo
tap_id: ivo://cadc.nrc.ca/sc2tap
todo_file_name: todo.txt
use_local_files: False
logging_level: DEBUG
log_to_file: True
log_file_directory: /usr/src/app/logs
collection: VLASS
archive: VLASS
stream: default
task_types: 
  - visit
features:
  use_file_names: False
  use_urls: True
