working_directory: /usr/src/app
netrc_filename: /usr/src/app/test_netrc
resource_id: ivo://cadc.nrc.ca/sc2repo
todo_file_name: todo.txt
use_local_files: True
logging_level: INFO
log_to_file: True
log_file_directory: /usr/src/app/logs
stream: default
archive: OMM
collection: OMM
task_types: 
  - ingest
  - modify
features:
  use_file_names: False
  use_urls: False
