working_directory: /usr/src/app
proxy_file_name: /usr/src/app/cadcproxy.pem
resource_id: ivo://cadc.nrc.ca/sc2repo
todo_file_name: todo.txt
logging_level: DEBUG
log_to_file: True
log_file_directory: /usr/src/app/logs
failure_log_file_name: failure_log.txt
retry_file_name: retries.txt
retry_failures: True
retry_count: 1
stream: raw
archive: OMM
collection: OMM
use_local_files: True
observe_execution: True
observable_directory: /usr/src/app/metrics
task_types:
  - store
  - ingest
  - modify
features:
  use_file_names: False
  use_urls: False
  run_in_airflow: False
  expects_retry: True
